"""
Pure domain EndOfCallDetector state machine.
Evaluates agent ending phrases, speech cancellations, silence timeouts, and call durations.
Zero external I/O or network dependencies.
"""

from __future__ import annotations

import difflib
import re
from dataclasses import dataclass
from enum import StrEnum


class DetectionAction(StrEnum):
    CONTINUE = "continue"
    HANG_UP = "hang_up"


@dataclass
class DetectionResult:
    action: DetectionAction
    reason: str | None = None
    confidence: float = 0.0


class EndOfCallDetector:
    """
    Pure domain state machine detecting call completion.

    Rules:
    1. Agent phrase matching: Fuzzy match against target goodbye phrase (similarity >= 0.75).
    2. Quiet window: Once matched, waits for quiet_window_sec (default 1.5s) to allow audio drain.
    3. Caller cancellation: If caller speaks during quiet window, hangup is cancelled.
    4. Silence timeout: If neither speaks for silence_timeout_sec, triggers hangup.
    5. Max duration: If call exceeds max_duration_sec, triggers hangup.
    """

    def __init__(
        self,
        ending_phrase: str,
        silence_timeout_sec: float = 12.0,
        max_duration_sec: float = 600.0,
        quiet_window_sec: float = 1.5,
        match_threshold: float = 0.75,
    ) -> None:
        self.ending_phrase = self._normalize(ending_phrase)
        self.silence_timeout_sec = silence_timeout_sec
        self.max_duration_sec = max_duration_sec
        self.quiet_window_sec = quiet_window_sec
        self.match_threshold = match_threshold

        # State tracking
        self._goodbye_detected_at: float | None = None
        self._last_speech_time: float = 0.0
        self._recent_agent_text: list[str] = []

    @staticmethod
    def _normalize(text: str) -> str:
        text = text.lower()
        text = re.sub(r"[^\w\s]", "", text)
        return " ".join(text.split())

    def record_caller_speech(self, timestamp: float) -> None:
        """Caller spoke. Update speech activity and cancel pending goodbye hangup."""
        self._last_speech_time = timestamp
        if self._goodbye_detected_at is not None:
            # Caller spoke back; cancel pending hangup to continue dialogue
            self._goodbye_detected_at = None

    def ingest_agent_token(self, token_text: str, timestamp: float) -> DetectionResult:
        """Ingest text token generated by agent."""
        clean = token_text.replace("\u2581", " ").strip()
        if not clean:
            return DetectionResult(DetectionAction.CONTINUE)

        self._last_speech_time = timestamp
        self._recent_agent_text.append(clean)
        if len(self._recent_agent_text) > 40:
            self._recent_agent_text.pop(0)

        # Check ending match
        rolling_text = self._normalize(" ".join(self._recent_agent_text))
        ratio = difflib.SequenceMatcher(None, self.ending_phrase, rolling_text).quick_ratio()

        if ratio >= self.match_threshold or self.ending_phrase in rolling_text:
            if self._goodbye_detected_at is None:
                self._goodbye_detected_at = timestamp

        return DetectionResult(DetectionAction.CONTINUE)

    def evaluate_tick(self, current_time: float, call_elapsed_sec: float) -> DetectionResult:
        """Periodic clock tick evaluation for time-based completion."""
        # 1. Check max duration
        if call_elapsed_sec >= self.max_duration_sec:
            return DetectionResult(
                DetectionAction.HANG_UP,
                reason="max_duration",
                confidence=1.0,
            )

        # 2. Check pending goodbye quiet window expiration
        if self._goodbye_detected_at is not None:
            if (current_time - self._goodbye_detected_at) >= self.quiet_window_sec:
                return DetectionResult(
                    DetectionAction.HANG_UP,
                    reason="agent_closed",
                    confidence=1.0,
                )

        # 3. Check silence timeout
        if self._last_speech_time > 0:
            silence_duration = current_time - self._last_speech_time
            if silence_duration >= self.silence_timeout_sec:
                return DetectionResult(
                    DetectionAction.HANG_UP,
                    reason="silence_timeout",
                    confidence=1.0,
                )

        return DetectionResult(DetectionAction.CONTINUE)
